Dev
MarkTiukov/WarGame pull request #2
Opened 2020-04-10 23:31 UTC by MarkTiukov

В последнем обновлении (которое, наверное относится к первому чекпоинту):
добавлен лут (разбросанные деньги по пустым клеткам), а также его генерация и отрисовка в консоли. 
Также была немного доделана отрисовка. 

Вообще, лут классно получился, например, чтобы понерфить его, надо будет поменять всего одну константу!!!! И таких примеров несколько;)

2020-04-11 15:18 UTC, akhtyamovpavel requested changes
В целом все хорошо, минорные замечания оставил - пока что могу поставить за эту часть 9, если пофиксишь - будет 10. Продолжай дальше!

2020-04-11 15:18 UTC, akhtyamovpavel commented on README.md
> +ОПИСАНИЕ СТРУКТУРЫ:
Лучше использовать Markdown полностью, чтобы явно было выделение на странице

2020-04-11 15:18 UTC, akhtyamovpavel commented on WarGame/.idea/uiDesigner.xml
> +<?xml version="1.0" encoding="UTF-8"?>
`.DS_Store` - в `.gitignore`

2020-04-11 15:18 UTC, akhtyamovpavel commented on WarGame/src/main/java/com/company/Main.java
> +        playableFractions = new Fraction[2];
Комментарии лучше не коммитить, git хранит версии кода

2020-04-11 15:18 UTC, akhtyamovpavel commented on WarGame/src/main/java/com/company/Main.java
> +        System.out.println("WELCOME TO WAR GAME");
Не желаешь текст в константы вынести?

2020-04-11 15:18 UTC, akhtyamovpavel commented on WarGame/src/main/java/com/company/Main.java
> +            case 2:
2 - магическая константа

2020-04-11 15:18 UTC, akhtyamovpavel commented on WarGame/src/main/java/com/company/Main.java
> +        while (result < 12) {
12 - магическая константа, лучше дать ей название

2020-04-11 15:18 UTC, akhtyamovpavel commented on WarGame/src/main/java/com/company/fields/Field.java
> +public class Field {
Следи за тем, чтобы это не превратилось в GOD-object

2020-04-11 15:18 UTC, akhtyamovpavel commented on WarGame/src/main/java/com/company/fields/FieldBuilderTwoPlayers.java
> +                    switch (this.random.nextInt(5)) { // 4 for money, 1 for double money
Не желаешь это в enum вынести, а то слишком много констант?

2020-04-11 15:18 UTC, akhtyamovpavel commented on WarGame/src/main/java/com/company/fields/FieldBuilderTwoPlayers.java
> +        int x2 = this.field.getSize() - 2 - random.nextInt(this.field.getSize() / 3);
Сложная математика, нельзя ли ее вынести в функцию?

2020-04-11 17:11 UTC, MarkTiukov commented on WarGame/.idea/uiDesigner.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Fixed

2020-04-11 17:11 UTC, MarkTiukov commented on WarGame/src/main/java/com/company/Main.java
> +        playableFractions = new Fraction[2];
Fixed

2020-04-11 17:16 UTC, MarkTiukov commented on WarGame/src/main/java/com/company/Main.java
> +            case 2:
А стоит ли её оборачивать в константу, есть лишнюю память. Типа это количество игроков, которое выбрал пользователь. Это даже понятно из условия. Ну то есть, это точно того стоит?

2020-04-11 17:40 UTC, MarkTiukov commented on WarGame/src/main/java/com/company/fields/Field.java
> +public class Field {
А как лучше это делать?

2020-04-11 23:17 UTC, MarkTiukov commented on WarGame/src/main/java/com/company/Main.java
> +        while (result < 12) {
Fixed

2020-04-11 23:18 UTC, MarkTiukov commented on WarGame/src/main/java/com/company/fields/FieldBuilderTwoPlayers.java
> +        int x2 = this.field.getSize() - 2 - random.nextInt(this.field.getSize() / 3);
Fixed

2020-04-11 23:26 UTC, MarkTiukov commented on WarGame/src/main/java/com/company/fields/FieldBuilderTwoPlayers.java
> +                    switch (this.random.nextInt(5)) { // 4 for money, 1 for double money
Не очень понял, что убирать в enum, но заменил switch на if, чтобы в случаях более сложной вероятности воспользоваться интервалами (типа если от а до б, то один вариант, от с до д другой и тд).

2020-04-12 00:03 UTC, MarkTiukov commented on README.md
> +ОПИСАНИЕ СТРУКТУРЫ:
Можете пояснить, что это значит?

2020-04-12 00:04 UTC, MarkTiukov commented on WarGame/src/main/java/com/company/Main.java
> +        System.out.println("WELCOME TO WAR GAME");
А в чем смысл, если это используется только тут и не имеет никакого дальнейшего использования?

2020-04-27 12:28 UTC, MarkTiukov commented
Произошел небольшой факап с удаление файлов( пришлось перезалить полностью папку с проектом

2020-05-01 18:59 UTC, MarkTiukov commented
Проект готов к проверке второго чекпоинта

2020-05-07 20:38 UTC, akhtyamovpavel commented on README.md
> +ОПИСАНИЕ СТРУКТУРЫ:
Посмотри в формат файла с расширением .md

2020-05-07 20:46 UTC, akhtyamovpavel approved these changes
Все отлично! Сливаю ветку!

2020-05-07 20:46 UTC, akhtyamovpavel commented on WarGame/src/main/java/com/company/fields/Field.java
> +public class Field {
Кажется, это получилось в итоге, теперь даже нет намеков

2020-05-07 20:46 UTC, merged